#!/bin/bash
#
# Escalate to human review when remediation attempts are exhausted.
# Creates an escalation report and optionally notifies via various channels.
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
STATE_DIR="${RALPH_PROJECT_STATE_DIR:-$PROJECT_DIR/state}"
PROJECT_NAME="${RALPH_PROJECT_NAME:-unknown}"

# Colors (same as ralph-secure.sh)
YELLOW='\033[1;33m'
NC='\033[0m'

# Log functions (same as ralph-secure.sh)
log_label() { printf "  %-16s │ %s\n" "$1" "$2"; }
log_warn()  { printf "  ${YELLOW}⚠${NC} %-14s │ %s\n" "$1" "$2"; }

# Arguments
ITERATION="${1:-0}"
SCAN_RESULT="${2:-UNKNOWN}"

# Timestamp
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
TIMESTAMP_LOCAL=$(date +"%Y-%m-%d %H:%M:%S %Z")

# Git info
GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
GIT_COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")

# Create escalation report
REPORT_FILE="$STATE_DIR/escalation-report-$(date +%s).md"

cat > "$REPORT_FILE" << EOF
# Security Escalation Report

**Generated:** $TIMESTAMP_LOCAL
**Status:** REQUIRES HUMAN REVIEW

---

## Summary

The automated security remediation loop has been exhausted without resolving all security findings.

| Field | Value |
|-------|-------|
| Project | $PROJECT_NAME |
| Iteration | $ITERATION |
| Branch | $GIT_BRANCH |
| Commit | $GIT_COMMIT |
| Final Scan Result | $SCAN_RESULT |

---

## What Happened

1. Claude Code implemented changes for user stories
2. Internal security scans (/security-scan skill with ASH) checked for vulnerabilities
3. Max iterations reached with stories still incomplete
4. Human review required to continue

---

## Security Findings

$(cat "$STATE_DIR/security-context.md" 2>/dev/null || echo "No context available")

---

## Audit Trail

\`\`\`
$(tail -20 "$STATE_DIR/security-audit.jsonl" 2>/dev/null | jq -r '"[\(.timestamp)] Iteration \(.iteration): \(.status)"' || echo "No audit trail available")
\`\`\`

---

## Recommended Actions

1. **Review the security findings** in detail
2. **Check if the issue is a false positive** - update Semgrep rules if so
3. **Manually fix the vulnerability** if it's a true positive
4. **Update the PRD** if the story requirements conflict with security
5. **Consider architectural changes** if the pattern is inherently insecure

---

## Files Changed

\`\`\`
$(git diff --name-only HEAD~1 2>/dev/null || echo "Unable to determine changed files")
\`\`\`

---

## How to Resume

After fixing the issues:

\`\`\`bash
# Re-run security scan to verify fix
./scripts/run-semgrep.sh \$(git diff --name-only HEAD~1)

# If passing, continue the loop
./ralph-secure.sh
\`\`\`

---

*This report was auto-generated by ralph-secure.sh*
EOF

echo ""
echo -e "  ${YELLOW}═══════════════════════════════════════════════════════════════${NC}"
echo -e "  ${YELLOW}⚠${NC} Escalation - Human Review Required"
echo -e "  ${YELLOW}═══════════════════════════════════════════════════════════════${NC}"
echo ""
log_label "Project" "$PROJECT_NAME"
log_label "Iteration" "$ITERATION"
log_label "Branch" "$GIT_BRANCH"
log_label "Result" "$SCAN_RESULT"
log_label "Report" "$REPORT_FILE"
echo ""

# Attempt to notify via various methods

# 1. Terminal bell
echo -e "\a"

# 2. macOS notification (if available)
if command -v osascript &> /dev/null; then
    osascript -e 'display notification "Security remediation failed after 3 attempts" with title "Ralph Loop Escalation" sound name "Basso"' 2>/dev/null || true
fi

# 3. Linux notification (if available)
if command -v notify-send &> /dev/null; then
    notify-send "Ralph Loop Escalation" "Security remediation failed after 3 attempts" -u critical 2>/dev/null || true
fi

# 4. Slack webhook (if configured)
SLACK_WEBHOOK="${RALPH_SLACK_WEBHOOK:-}"
if [ -n "$SLACK_WEBHOOK" ]; then
    curl -s -X POST -H 'Content-type: application/json' \
        --data "{\"text\":\":rotating_light: *Security Escalation* - Project: $PROJECT_NAME - Branch: $GIT_BRANCH - $SCAN_RESULT\"}" \
        "$SLACK_WEBHOOK" > /dev/null 2>&1 || true
fi

echo "  Review the report and fix the issues manually."
echo ""

exit 1
