#!/bin/bash
#
# Report pre-existing security vulnerabilities to GitHub Issues.
# Creates issues for tracking inherited security debt (with deduplication).
#
# Usage:
#   report-preexisting.sh <findings_file> <project_name>
#
# Environment:
#   RALPH_CREATE_SECURITY_ISSUES - Set to "false" to skip issue creation (default: true)
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
STATE_DIR="${RALPH_PROJECT_STATE_DIR:-$PROJECT_DIR/state}"
TARGET_DIR="${RALPH_TARGET_DIR:-$(pwd)}"

# Arguments
FINDINGS_FILE="${1:-}"
PROJECT_NAME="${2:-${RALPH_PROJECT_NAME:-unknown}}"

# Check if issue creation is enabled (default: true)
CREATE_ISSUES="${RALPH_CREATE_SECURITY_ISSUES:-true}"

# Logging helpers
log_info()  { printf "  %-16s │ %s\n" "$1" "$2"; }
log_ok()    { printf "  \033[0;32m✓\033[0m %-14s │ %s\n" "$1" "$2"; }
log_warn()  { printf "  \033[1;33m⚠\033[0m %-14s │ %s\n" "$1" "$2"; }

# Validate inputs
if [ -z "$FINDINGS_FILE" ]; then
    echo "Usage: $0 <findings_file> [project_name]" >&2
    exit 1
fi

if [ ! -f "$FINDINGS_FILE" ]; then
    echo "Findings file not found: $FINDINGS_FILE" >&2
    exit 1
fi

# Check if gh CLI is available
if ! command -v gh &> /dev/null; then
    log_warn "Skipped" "gh CLI not found - cannot create GitHub issues"
    exit 0
fi

# Check if gh is authenticated
if ! gh auth status &> /dev/null 2>&1; then
    log_warn "Skipped" "gh not authenticated - run 'gh auth login'"
    exit 0
fi

# If issue creation is disabled, just log and exit
if [ "$CREATE_ISSUES" = "false" ]; then
    log_info "Skipped" "GitHub issue creation (RALPH_CREATE_SECURITY_ISSUES=false)"
    exit 0
fi

# Ensure required labels exist (create if missing)
ensure_labels_exist() {
    cd "$TARGET_DIR"

    # Create security-debt label if missing
    if ! gh label list --json name -q '.[].name' 2>/dev/null | grep -q "^security-debt$"; then
        gh label create "security-debt" \
            --description "Pre-existing security vulnerabilities tracked for remediation" \
            --color "d73a4a" > /dev/null 2>&1 || true
    fi

    # Create ralph-detected label if missing
    if ! gh label list --json name -q '.[].name' 2>/dev/null | grep -q "^ralph-detected$"; then
        gh label create "ralph-detected" \
            --description "Detected by Ralph Loop security scanning" \
            --color "0366d6" > /dev/null 2>&1 || true
    fi
}

ensure_labels_exist

# Get unique files with findings
FILES=$(jq -r '[.[].file // empty] | unique[]' "$FINDINGS_FILE" 2>/dev/null || true)

if [ -z "$FILES" ]; then
    log_info "No files" "No pre-existing findings to report"
    exit 0
fi

# Track created issues
ISSUES_CREATED=0
ISSUES_SKIPPED=0

# Process each file with findings
while IFS= read -r file; do
    [ -z "$file" ] && continue

    # Get findings for this file
    FILE_FINDINGS=$(jq -c "[.[] | select(.file == \"$file\")]" "$FINDINGS_FILE" 2>/dev/null)
    FINDING_COUNT=$(echo "$FILE_FINDINGS" | jq 'length')

    if [ "$FINDING_COUNT" = "0" ]; then
        continue
    fi

    # Check if issue already exists for this file
    EXISTING_ISSUE=$(cd "$TARGET_DIR" && gh issue list \
        --label "security-debt" \
        --search "Security: Pre-existing vulnerabilities in $file" \
        --json number,title \
        -q '.[0].number' 2>/dev/null || true)

    if [ -n "$EXISTING_ISSUE" ]; then
        log_info "Exists" "Issue #$EXISTING_ISSUE already tracks $file"
        ISSUES_SKIPPED=$((ISSUES_SKIPPED + 1))
        continue
    fi

    # Build findings list for issue body
    FINDINGS_MD=$(echo "$FILE_FINDINGS" | jq -r '.[] | "- **[\(.severity // "UNKNOWN")]** Line \(.line // "?"): `\(.rule_id // "unknown")`\n  \(.message // "No message")"')

    # Create new issue
    ISSUE_BODY=$(cat <<EOF
## Pre-Existing Security Findings

Found during Ralph Loop iteration for **$PROJECT_NAME**.

### Findings in \`$file\`:

$FINDINGS_MD

### Context

- These vulnerabilities existed before the current work
- They were not introduced by the current story
- Flagged for tracking and remediation

### Recommended Actions

1. Review each finding for false positives
2. If legitimate, prioritize fix based on severity
3. If false positive, add to baseline exceptions

---
*Generated by Securing Ralph Loop*
EOF
)

    NEW_ISSUE=$(cd "$TARGET_DIR" && gh issue create \
        --title "Security: Pre-existing vulnerabilities in $file" \
        --body "$ISSUE_BODY" \
        --label "security-debt,ralph-detected" 2>&1) || true

    if echo "$NEW_ISSUE" | grep -q "https://"; then
        ISSUE_NUM=$(echo "$NEW_ISSUE" | grep -oE '[0-9]+$')
        log_ok "Created" "Issue #$ISSUE_NUM for $file"
        ISSUES_CREATED=$((ISSUES_CREATED + 1))
    else
        log_warn "Failed" "Could not create issue for $file: $NEW_ISSUE"
    fi

done <<< "$FILES"

# Summary
if [ "$ISSUES_CREATED" -gt 0 ] || [ "$ISSUES_SKIPPED" -gt 0 ]; then
    log_info "Summary" "$ISSUES_CREATED created, $ISSUES_SKIPPED already existed"
fi

exit 0
